export enum ConfirmationCodeLabel {
   CONFIRMATION_CODE_LABEL_UNSPECIFIED = 'CONFIRMATION_CODE_LABEL_UNSPECIFIED',
   CONFIRMATION_CODE = 'CONFIRMATION_CODE',
   CONFIRMATION_NUMBER = 'CONFIRMATION_NUMBER',
   RESERVATION_NUMBER = 'RESERVATION_NUMBER',
}
