export enum DateFormat {
   DATE_FORMAT_UNSPECIFIED = 'DATE_FORMAT_UNSPECIFIED',
   DATE_TIME = 'DATE_TIME',
   DATE_ONLY = 'DATE_ONLY',
   TIME_ONLY = 'TIME_ONLY',
   DATE_TIME_YEAR = 'DATE_TIME_YEAR',
   DATE_YEAR = 'DATE_YEAR',
   YEAR_MONTH = 'YEAR_MONTH',
   YEAR_MONTH_DAY = 'YEAR_MONTH_DAY',
}
