export enum MultipleDevicesAndHoldersAllowedStatus {
   STATUS_UNSPECIFIED = 'STATUS_UNSPECIFIED',
   MULTIPLE_HOLDERS = 'MULTIPLE_HOLDERS',
   ONE_USER_ALL_DEVICES = 'ONE_USER_ALL_DEVICES',
   ONE_USER_ONE_DEVICE = 'ONE_USER_ONE_DEVICE',
}
