export enum TransitOption {
   TRANSIT_OPTION_UNSPECIFIED = 'TRANSIT_OPTION_UNSPECIFIED',
   ORIGIN_AND_DESTINATION_NAMES = 'ORIGIN_AND_DESTINATION_NAMES',
   ORIGIN_AND_DESTINATION_CODES = 'ORIGIN_AND_DESTINATION_CODES',
   ORIGIN_NAME = 'ORIGIN_NAME',
}
