export enum ViewUnlockRequirement {
   VIEW_UNLOCK_REQUIREMENT_UNSPECIFIED = 'VIEW_UNLOCK_REQUIREMENT_UNSPECIFIED',
   UNLOCK_NOT_REQUIRED = 'UNLOCK_NOT_REQUIRED',
   UNLOCK_REQUIRED_TO_VIEW = 'UNLOCK_REQUIRED_TO_VIEW',
}
