export type BarcodeType = 
   | 'BARCODE_TYPE_UNSPECIFIED'
   | 'AZTEC'
   | 'CODE_39'
   | 'CODE_128'
   | 'CODABAR'
   | 'DATA_MATRIX'
   | 'EAN_8'
   | 'EAN_13'
   | 'ITF_14'
   | 'PDF_417'
   | 'QR_CODE'
   | 'UPC_A'
   | 'TEXT_ONLY'
;